[2022-08-31 17:33:50,821] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-08-31T17:33:48.255662+00:00 [queued]>
[2022-08-31 17:33:50,864] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-08-31T17:33:48.255662+00:00 [queued]>
[2022-08-31 17:33:50,869] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 17:33:50,871] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-31 17:33:50,874] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 17:33:50,946] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-08-31 17:33:48.255662+00:00
[2022-08-31 17:33:50,957] {standard_task_runner.py:52} INFO - Started process 253 to run task
[2022-08-31 17:33:50,995] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-08-31T17:33:48.255662+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmppjd3mdf6', '--error-file', '/tmp/tmpbc1_mwsa']
[2022-08-31 17:33:50,999] {standard_task_runner.py:80} INFO - Job 4: Subtask load_seed_data_once
[2022-08-31 17:33:51,278] {task_command.py:371} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-08-31T17:33:48.255662+00:00 [running]> on host 4a8ffecbc2e6
[2022-08-31 17:33:51,681] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-08-31T17:33:48.255662+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-31T17:33:48.255662+00:00
[2022-08-31 17:33:51,687] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-31 17:33:51,690] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-08-31 17:33:51,722] {subprocess.py:85} INFO - Output:
[2022-08-31 17:34:01,629] {subprocess.py:92} INFO - [0m17:34:01  Running with dbt=1.2.1
[2022-08-31 17:34:01,707] {subprocess.py:92} INFO - [0m17:34:01  Partial parse save file not found. Starting full parse.
[2022-08-31 17:34:07,646] {subprocess.py:92} INFO - [0m17:34:07  Found 5 models, 0 tests, 0 snapshots, 0 analyses, 506 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
[2022-08-31 17:34:07,655] {subprocess.py:92} INFO - [0m17:34:07
[2022-08-31 17:34:14,925] {subprocess.py:92} INFO - [0m17:34:14  Concurrency: 1 threads (target='dev')
[2022-08-31 17:34:14,929] {subprocess.py:92} INFO - [0m17:34:14
[2022-08-31 17:34:14,957] {subprocess.py:92} INFO - [0m17:34:14  1 of 3 START seed file PUBLIC.bookings_1 ....................................... [RUN]
[2022-08-31 17:34:18,903] {subprocess.py:92} INFO - [0m17:34:18  1 of 3 OK loaded seed file PUBLIC.bookings_1 ................................... [[32mINSERT 23[0m in 3.94s]
[2022-08-31 17:34:18,920] {subprocess.py:92} INFO - [0m17:34:18  2 of 3 START seed file PUBLIC.bookings_2 ....................................... [RUN]
[2022-08-31 17:34:21,853] {subprocess.py:92} INFO - [0m17:34:21  2 of 3 OK loaded seed file PUBLIC.bookings_2 ................................... [[32mINSERT 16[0m in 2.93s]
[2022-08-31 17:34:21,865] {subprocess.py:92} INFO - [0m17:34:21  3 of 3 START seed file PUBLIC.customers ........................................ [RUN]
[2022-08-31 17:34:24,860] {subprocess.py:92} INFO - [0m17:34:24  3 of 3 OK loaded seed file PUBLIC.customers .................................... [[32mINSERT 9[0m in 2.98s]
[2022-08-31 17:34:24,889] {subprocess.py:92} INFO - [0m17:34:24
[2022-08-31 17:34:24,893] {subprocess.py:92} INFO - [0m17:34:24  Finished running 3 seeds in 0 hours 0 minutes and 17.23 seconds (17.23s).
[2022-08-31 17:34:24,990] {subprocess.py:92} INFO - [0m17:34:24
[2022-08-31 17:34:25,000] {subprocess.py:92} INFO - [0m17:34:24  [32mCompleted successfully[0m
[2022-08-31 17:34:25,008] {subprocess.py:92} INFO - [0m17:34:25
[2022-08-31 17:34:25,019] {subprocess.py:92} INFO - [0m17:34:25  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-08-31 17:34:26,068] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-31 17:34:26,128] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220831T173348, start_date=20220831T173350, end_date=20220831T173426
[2022-08-31 17:34:26,175] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-31 17:34:26,226] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
